name: build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  plugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - uses: actions/setup-node@v4
        with:
          node-version-file: web/package.json
          cache-dependency-path: web/package-lock.json
      - uses: actions/setup-go@v5
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum

      - name: Build artifact
        run: python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: dist
          if-no-files-found: error
          include-hidden-files: true
