name: merge

on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install commitlint
        run: |
          npm install @commitlint/cli @commitlint/config-conventional
          echo 'extends: ["@commitlint/config-conventional"]' > .commitlintrc.yaml
      - name: Run commitlint on pull request title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | npx commitlint
